server:
  port: 8889 #服务端口，自定义
spring:
  application:
    name: teqin
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:5432/teqin
      username: postgres
      password: postgres
      initial-size: 10
      min-idle: 10
      max-active: 20
      max-wait: 60000
  mvc:
    cors:
      allow-credentials: true
      allowed-headers: "*"
      allowed-methods: "*"
    async:
      request-timeout: 60000
  jackson:
    default-property-inclusion: always
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
      location: d://base_img//tmp
jwt:
  issuer: teqin
  subject: teqin_
  secret: teqin_
  age: 43200 #token有效期12小时
file:
  uploadPath: d://base_img
#缓冲区半径(米)
buffer:
  radius: 500.0
#点位名称字段
pointFieldName: mingcheng
#基础名称字段
infoFieldName: title
#高速公路配置
highway:
  #类型ID
  typeId: 8374ec30c3724f179074c9186bd716a9
  #基本信息类型ID
  basicInfoTypeId: 72cf70077c0148d4b89448072989ebda
#高速铁路配置
railway:
  #类型ID
  typeId: 530ed72b535d4b9a858c0818f6aa8c18
  #基本信息类型
  basicInfoTypeId: dd63a9b60a5141ba8db5c927c14b2bba
#现场配置
site:
  typeId: 580a7cd1b2bc4a1fb3f851eac8ae4394
  #基本信息类型ID
  basicInfoTypeId: a2422d3f17804aadb8b11e03bfb64386
  #内设机构类型ID
  insideOrgTypeId: d99b5b8bbca64353a6fd01d78f03ba78
  #主要建筑类型ID
  mainBuildingsTypeId: 1125e5adfc80497988cd2921fd2fed3b
  #重要部位类型ID
  importantPartTypeId: b1e855466e214e148a61d81d40bcacef
  #四邻类型ID
  fourNeighborsTypeId: 40656ab0011140ea80926e1a34deb4e0
  #停车场类型ID
  parkingTypeId: fe51d659d1824a8390f667dc83ccc220
  #重点部位类型ID
  importantRegionTypeId: 9178ce1e12b645f4840480068d5e859c
  #主要建筑特殊字段
  mainBuildings:
    vipNameField: guibinxiuxishimingcheng
    vipSeatField: guibinxiuxishizuowei
    meetingRoomNameField: huiyishimingcheng
    meetingRoomSeatField: huiyishizuowei
    diningRoomNameField: cantingmingcheng
    diningRoomSeatField: cantingzuowei

#住地配置
residence:
  typeId: 00374c44bb444f9da3f95ae63915ebca
  #基本信息类型ID
  basicInfoTypeId: 14fdd3180ac34588a80aa5baf624071b
  #内设机构类型ID
  insideOrgTypeId: c1c1e687bdb54a728fa68c0168cc7d61
  #主要建筑类型ID
  mainBuildingsTypeId: 12f5aeb6bfa84df29d4d3f0f4b20ee34
  #重要部位类型ID
  importantPartTypeId: f3bc6d787877450892891d333adbc3ac
  #四邻类型ID
  fourNeighborsTypeId: d0fdd413c55e456da7ac15104652f315
  #停车场类型ID
  parkingTypeId: 912905c0e8bc42818e13a58c9626826b
  #主要建筑特殊字段
  mainBuildings:
    vipNameField: guibinxiuxishimingcheng
    vipSeatField: guibinxiuxishizuowei
    meetingRoomNameField: huiyishimingcheng
    meetingRoomSeatField: huiyishizuowei
    diningRoomNameField: cantingmingcheng
    diningRoomSeatField: cantingzuowei
#道路配置
road:
  typeId: dfd4cb986b9c433da539683bfd3d569b
  basicInfoTypeId: a9bc87316f394049a5e2f593a6ab42ae
#资源列表配置
treeNode:
  keyFocus: 重点人员
  securityCheck: 安检站,安检员
  site:
    key1: 管理机构,物业,保安,内设机构
    key2: 会议室,餐厅,厨房,主要建筑
    key3: 出入口,电梯,步行梯,扶梯,监控摄像头,新风外部进风口,燃气系统阀门,重要部位
  siteAround:
    key1: 四邻情况
    key2: 出入口,电梯,步行梯,扶梯,井盖,监控摄像头,停车场,新风外部进风口,制高点,重要部位
  residence:
    key1: 管理机构,物业,保安,内设机构
    key2: 客房,会议室,餐厅,厨房,主要建筑
    key3: 出入口,电梯,步行梯,扶梯,监控摄像头,新风外部进风口,燃气系统阀门,重要部位
  residenceAround:
    key1: 四邻情况
    key2: 出入口,电梯,步行梯,扶梯,井盖,监控摄像头,制高点
  cityRoad: 医院,复杂村庄,工地,复杂地段,制高点,其他情况,丁字路口,红绿灯,公交站,危爆场所,主线桥,跨线桥,限高,学校,十字路口,井盖
  railway: 高铁低路基路段,高铁复杂路段,高铁两侧危爆物品厂库,高铁下穿道路,高铁沿线复杂村镇,高铁基站,高铁四电所,高铁道口,高铁涵洞,高铁平安道口,高铁桥梁,高铁隧道,高铁制高点
  highway: 高速制高点,高速桥梁,高速互通,高速涵洞,高速服务区,高速出入收费站,高速出入口,高速基站
  police: 交通哨,固定哨,随卫哨,社控哨,昼夜哨,制高点哨,游动哨,快反力量,无人机反制
  car: 警车
  cordon: 警戒线
  emergency: 避险点,应急医院,消防车,应急路线
communityData:
  tables: t_dc_ci_rs,t_dc_grid,t_dc_party_individual,t_dc_area_building_info,t_dc_area_room_info,t_dc_area_room_record,t_res_tag_dict,t_zz_manager_info
  view: view.sql
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.xaxc.teqin.model.entity
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.xaxc.teqin: DEBUG
  file:
    name: logs/teqin.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 180